logging:
  level:
    root: INFO

server:
  port: 8000

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/mindb
    username: root
    password: min
  data:
    redis:
      host: 127.0.0.1
      port: 6379